// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package csql

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ILLEGAL-0]
	_ = x[EOF-1]
	_ = x[WS-2]
	_ = x[STAR-3]
	_ = x[COMMA-4]
	_ = x[DOT-5]
	_ = x[LPAREN-6]
	_ = x[RPAREN-7]
	_ = x[LBRACKET-8]
	_ = x[RBRACKET-9]
	_ = x[EQ-10]
	_ = x[NEQ-11]
	_ = x[LT-12]
	_ = x[LTE-13]
	_ = x[GT-14]
	_ = x[GTE-15]
	_ = x[PLUS-16]
	_ = x[MINUS-17]
	_ = x[SLASH-18]
	_ = x[PERCENT-19]
	_ = x[SEMICOLON-20]
	_ = x[SELECT-21]
	_ = x[DISTINCT-22]
	_ = x[COUNT-23]
	_ = x[SUM-24]
	_ = x[MAX-25]
	_ = x[MIN-26]
	_ = x[AVG-27]
	_ = x[AS-28]
	_ = x[FROM-29]
	_ = x[CROSS-30]
	_ = x[INNER-31]
	_ = x[LEFT-32]
	_ = x[RIGHT-33]
	_ = x[FULL-34]
	_ = x[OUTER-35]
	_ = x[JOIN-36]
	_ = x[ON-37]
	_ = x[WHERE-38]
	_ = x[AND-39]
	_ = x[OR-40]
	_ = x[NOT-41]
	_ = x[IN-42]
	_ = x[IS-43]
	_ = x[BETWEEN-44]
	_ = x[WITHIN-45]
	_ = x[GROUP-46]
	_ = x[BY-47]
	_ = x[EVERY-48]
	_ = x[LIMIT-49]
	_ = x[NULL-50]
	_ = x[TRUE-51]
	_ = x[FALSE-52]
	_ = x[STRING-53]
	_ = x[NUMERIC-54]
	_ = x[IDENT-55]
	_ = x[COMMENT-56]
}

const _TokenType_name = "ILLEGALEOFWSSTARCOMMADOTLPARENRPARENLBRACKETRBRACKETEQNEQLTLTEGTGTEPLUSMINUSSLASHPERCENTSEMICOLONSELECTDISTINCTCOUNTSUMMAXMINAVGASFROMCROSSINNERLEFTRIGHTFULLOUTERJOINONWHEREANDORNOTINISBETWEENWITHINGROUPBYEVERYLIMITNULLTRUEFALSESTRINGNUMERICIDENTCOMMENT"

var _TokenType_index = [...]uint8{0, 7, 10, 12, 16, 21, 24, 30, 36, 44, 52, 54, 57, 59, 62, 64, 67, 71, 76, 81, 88, 97, 103, 111, 116, 119, 122, 125, 128, 130, 134, 139, 144, 148, 153, 157, 162, 166, 168, 173, 176, 178, 181, 183, 185, 192, 198, 203, 205, 210, 215, 219, 223, 228, 234, 241, 246, 253}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
