// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ILLEGAL-0]
	_ = x[EOF-1]
	_ = x[COMMENT-2]
	_ = x[WS-3]
	_ = x[STAR-4]
	_ = x[COMMA-5]
	_ = x[DOT-6]
	_ = x[LPAREN-7]
	_ = x[RPAREN-8]
	_ = x[LBRACKET-9]
	_ = x[RBRACKET-10]
	_ = x[EQ-11]
	_ = x[NEQ-12]
	_ = x[LT-13]
	_ = x[LTE-14]
	_ = x[GT-15]
	_ = x[GTE-16]
	_ = x[PLUS-17]
	_ = x[MINUS-18]
	_ = x[SLASH-19]
	_ = x[PERCENT-20]
	_ = x[SEMICOLON-21]
	_ = x[SELECT-22]
	_ = x[DISTINCT-23]
	_ = x[COUNT-24]
	_ = x[SUM-25]
	_ = x[MAX-26]
	_ = x[MIN-27]
	_ = x[AVG-28]
	_ = x[AS-29]
	_ = x[FROM-30]
	_ = x[OVER-31]
	_ = x[WHERE-32]
	_ = x[AND-33]
	_ = x[OR-34]
	_ = x[NOT-35]
	_ = x[IN-36]
	_ = x[IS-37]
	_ = x[BETWEEN-38]
	_ = x[WITHIN-39]
	_ = x[GROUP-40]
	_ = x[BY-41]
	_ = x[ORDER-42]
	_ = x[ASC-43]
	_ = x[DESC-44]
	_ = x[LIMIT-45]
	_ = x[NULL-46]
	_ = x[EVERY-47]
	_ = x[CONSUME-48]
	_ = x[SELF-49]
	_ = x[EDGE-50]
	_ = x[TREE-51]
	_ = x[JOIN-52]
	_ = x[ON-53]
	_ = x[LEFT-54]
	_ = x[RIGHT-55]
	_ = x[LIKE-56]
	_ = x[STRING-57]
	_ = x[NUMERIC-58]
	_ = x[DURATION-59]
	_ = x[TRUE-60]
	_ = x[FALSE-61]
	_ = x[IDENT-62]
}

const _TokenType_name = "ILLEGALEOFCOMMENTWSSTARCOMMADOTLPARENRPARENLBRACKETRBRACKETEQNEQLTLTEGTGTEPLUSMINUSSLASHPERCENTSEMICOLONSELECTDISTINCTCOUNTSUMMAXMINAVGASFROMOVERWHEREANDORNOTINISBETWEENWITHINGROUPBYORDERASCDESCLIMITNULLEVERYCONSUMESELFEDGETREEJOINONLEFTRIGHTLIKESTRINGNUMERICDURATIONTRUEFALSEIDENT"

var _TokenType_index = [...]uint16{0, 7, 10, 17, 19, 23, 28, 31, 37, 43, 51, 59, 61, 64, 66, 69, 71, 74, 78, 83, 88, 95, 104, 110, 118, 123, 126, 129, 132, 135, 137, 141, 145, 150, 153, 155, 158, 160, 162, 169, 175, 180, 182, 187, 190, 194, 199, 203, 208, 215, 219, 223, 227, 231, 233, 237, 242, 246, 252, 259, 267, 271, 276, 281}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
